baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = "hugo-pathways-theme"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

publishURL = "http://intro-to-esports.lsupathways.org"

[params]
  editURL = "https://github.com/lsu-ddem/intro-to-esports"
  description = "Educational material for Pre-Engineering"
  author = "Erin Demastes"
  showVisitedLinks = true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Educational material for Pre-Engineering"
weight = 1
languageName = "English"




