
backend:
  name: git-gateway

media_folder: "/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  # Unit 1
  - name: "Professional Esports"
    label: "Professional Esports"
    folder: "content/1_Professional Esports"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Amateur Esports"
    label: "Amateur Esports"
    folder: "content/2_Amateur Esports"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  # #Projects
  # - name: "Unit 1 - Lesson 2 - Project 1"
  #   label: "Unit 1 - Lesson 2 - Project 1"
  #   folder: "content/1_Unit_1/2_Lesson_2/1_Project_1"
  #   create: true
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Order", name: "weight", widget: "number" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  # - name: "Unit 1 - Lesson 2 - Project 2"
  #   label: "Unit 1 - Lesson 2 - Project 2"
  #   folder: "content/1_Unit_1/2_Lesson_2/2_Project_2"
  #   create: true
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Order", name: "weight", widget: "number" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  # - name: "Unit 1 - Lesson 2 - Project 3"
  #   label: "Unit 1 - Lesson 2 - Project 3"
  #   folder: "content/1_Unit_1/2_Lesson_2/3_Project_3"
  #   create: true
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Order", name: "weight", widget: "number" }
  #     - { label: "Body", name: "body", widget: "markdown" }

  #Back to lessons
  - name: "Collegiate and High School Esports"
    label: "Collegiate and High School Esports"
    folder: "content/3_Collegiate and High School Esports"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  
  - name: "Project"
    label: "Project"
    folder: "content/4_Project"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  
  - name: "Esports and Sports"
    label: "Esports and Sports"
    folder: "content/5_Esports and Sports"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "Esports Tournaments"
    label: "Esports Tournaments"
    folder: "content/6_Esports Tournaments"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "Esports Marketing"
    label: "Esports Marketing"
    folder: "content/7_Esports Marketing"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "Esports Production"
    label: "Esports Production"
    folder: "content/8_Esports Production"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

    - name: "Esports Content Creation"
    label: "Esports Content Creation"
    folder: "content/9_Esports Content Creation"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }